sudo: required
dist: trusty
language: node_js
node_js:
  - '10'
addons:
  chrome: stable
env:
  - TESTCAFE_URL=http://127.0.0.1
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
services:
  - docker
before_install:
  - npm install -g testcafe
install:
  - npm ci
before_script:
  - npm run build:lib
  - npm run build:app
  # start container for e2e test
  - docker run -p 127.0.0.1:80:80 -d $(docker build -q .)
script:
  - curl 127.0.0.1
  - npm run test -- --code-coverage --watch=false
  - npm run test:e2e
after_script:
  - docker system prune --volumes --all -f
before_deploy:
  - npm run copy:readme
  - cd dist/ngrx-store-storagesync
deploy:
  provider: npm
  edge: true
  email: '$NPM_EMAIL'
  api_key: '$NPM_API_TOKEN'
  skip_cleanup: true
  on:
    tags: true
after_success:
  - chmod +x scripts/netlify.sh
  - scripts/netlify.sh
