language: node_js
branches:
  only:
    - master
node_js:
  - "10"
script:
  - npm run lint
  - npm run test
before_deploy:
  - npm run build
deploy:
    provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_API_TOKEN"
    skip_cleanup: true
    on:
      tags: true