language: node_js
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
node_js:
  - "10"
script:
  - npm run test
before_deploy:
  - npm run build
deploy:
    provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_API_TOKEN"
    skip_cleanup: true
    on:
      tags: true
after_deploy:
  - "curl -X POST -d {} https://api.netlify.com/build_hooks/5cd048d41ac52d25f732a104"