language: node_js
node_js:
  - "10.13.0"
deploy:
  provider: script
  script: 
    - if [ "$TRAVIS_BRANCH" = "master" ]; then "npm test"; fi
    - if [ "$TRAVIS_BRANCH" = "release" ]; then "npm run prepublish"; fi
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    recipients:
    - larskniep@gmail.com
    on_success: change
    on_failure: always
branches:
  only:
    - release
    - master
