sudo: required
dist: trusty
language: node_js
node_js:
  - '10'
addons:
  chrome: stable
  firefox: latest
env:
  - TESTCAFE_URL='http://127.0.0.1'
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
services:
  - docker
before_install:
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"[Travis]"* ]]; then travis_terminate 0; fi
install:
  - npm ci
before_script:
  - npm run build:app
  - docker run -p 80:80 -d $(docker build -q .)
script:
  - npm run test -- --code-coverage --watch=false
  - npm run test:e2e
after_script:
  - docker system prune --volumes --all -f
  - chmod +x .travis/update-version.sh
  - .travis/update-version.sh
before_deploy:
  - npm run build:lib
  - npm run copy:readme
  - cd dist/ngrx-store-storagesync
deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_API_TOKEN'
  skip_cleanup: true
  on:
    tags: true
