sudo: required
dist: trusty
language: node_js
addons:
  chrome: "77.0.3865"
env:
  - TESTCAFE_URL=http://127.0.0.1
node_js:
  - "10"
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
services:
  - docker
install:
  - npm ci
before_script:
  - npm run build:app
  - docker build -t ngrx_store_storagesync .
  - docker run -p 80:80 -d ngrx_store_storagesync
script:
  - npm run test -- --code-coverage --watch=false
  - npm run test:e2e
after_script:
  - docker system prune -f
before_deploy:
  - npm run build:lib
  - npm run copy:readme
  - cd dist/ngrx-store-storagesync
deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_API_TOKEN'
  skip_cleanup: true
  on:
    tags: true
