language: node_js
node_js:
  - "10"
script:
  - npm run test
before_install:
  - echo $TRAVIS_TAG
before_deploy:
  - npm run build
deploy:
    provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_API_TOKEN"
    skip_cleanup: true
    on:
      tags: true

notifications:
  email:
    recipients:
      - "$NPM_EMAIL"
    on_success: change
    on_failure: always
