language: node_js
node_js:
  - "10"
before_install:
  - echo $TRAVIS_TAG
deploy:
  - provider: script
    script: "cp .npmrc.template $HOME/.npmrc && npm publish"   
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: "npm test"  
    skip_cleanup: true 
    on:
      branch: master

notifications:
  email:
    recipients:
      - larskniep@gmail.com
    on_success: change
    on_failure: always
